-- MySQL Script generated by MySQL Workbench
-- Fri Jun  3 21:58:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `app` DEFAULT CHARACTER SET utf8 ;
USE `app` ;

-- -----------------------------------------------------
-- Table `app`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `iduser` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`iduser`));


-- -----------------------------------------------------
-- Table `app`.`action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app`.`action` (
  `idaction` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`idaction`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app`.`action_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app`.`action_history` (
  `idaction_history` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `date` DATETIME NULL,
  `description` VARCHAR(45) NULL,
  `idaction` INT NULL,
  `iduser` INT NULL,
  PRIMARY KEY (`idaction_history`),
  INDEX `user_idx` (`iduser` ASC) VISIBLE,
  INDEX `action_idx` (`idaction` ASC) VISIBLE,
  CONSTRAINT `action`
    FOREIGN KEY (`idaction`)
    REFERENCES `app`.`action` (`idaction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user`
    FOREIGN KEY (`iduser`)
    REFERENCES `app`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
